import BasicNavbar from "./components/Navbar";
import Head from "next/head";
function Blog() {
  return (
    <>
     <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicNavbar />
    <div>
      <h1>this is Blog page</h1>
    </div>
    </>
  );
}

export default Blog;
